### ISSUE TITLE
Error message showing "patch.xp3 is not XP3 archive or unsupported" - Manual Install, NO Vita patches

### ISSUE THREAD

**Issue by ccapwell** [leycec/fsnrnue#14]
Running gamemoderun /home/chas/.local/share/lutris/runners/wine/lutris-6.1-3-x86_64/bin/wine /home/chas/Games/fate-stay-night-realta-nua-ultimate-edition/drive_c/Program Files/Fate／stay night[Realta Nua] Ultimate Edition/Fate.exe
Initial process has started with pid 61272
Start monitoring process.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
user.reg:725: Malformed value '"HDA NVidia HDMI/DP,pc"=3 (js)"="disabled"'
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
11:27:20 (info) Loading configuration file "C:\Program Files\Fate^stay night[Realta Nua] Ultimate Edition\Fate.cf" failed (ignoring) : file not found.
11:27:20 (info) Loading configuration file "C:\Program Files\Fate^stay night[Realta Nua] Ultimate Edition\savedata\Fate.cfu" failed (ignoring) : file not found.
11:27:20 (info) Data path : file://./c/program files/fate^stay night[realta nua] ultimate edition/savedata/
11:27:20 Kirikiri Z Executable core /1.4.0.8 (Compiled on Dec 25 2017 03:47:15) TJS2/2.4.28 Copyright (C) 1997-2013 W.Dee and contributors All rights reserved.
11:27:20 The details of version information can be perused if -about is attached and started. 
11:27:20 Program started on Windows 7 6.1.3505 Service Pack 1 (Win32)
11:27:20 (info) Rebuilding Auto Path Table ...
11:27:20 (info) Total 0 file(s) found, 0 file(s) activated. (0ms)
11:27:20 (info) Total physical memory : 21704876032
11:27:20 (info) Selected project directory : file://./c/program files/fate^stay night[realta nua] ultimate edition/data.xp3>
11:27:20 (info) CPU #0 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:yes  AVX2:yes  FMA3:yes  AES:yes  RDRAND:yes  RDSEED:yes  Intel(GenuineIntel) [Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz]  CPUID(1)/EAX=000A0655 CPUID(1)/EBX=00100800
11:27:20 (info) CPU #1 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:yes  AVX2:yes  FMA3:yes  AES:yes  RDRAND:yes  RDSEED:yes  Intel(GenuineIntel) [Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz]  CPUID(1)/EAX=000A0655 CPUID(1)/EBX=02100800
11:27:20 (info) CPU #2 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:yes  AVX2:yes  FMA3:yes  AES:yes  RDRAND:yes  RDSEED:yes  Intel(GenuineIntel) [Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz]  CPUID(1)/EAX=000A0655 CPUID(1)/EBX=04100800
11:27:20 (info) CPU #3 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:yes  AVX2:yes  FMA3:yes  AES:yes  RDRAND:yes  RDSEED:yes  Intel(GenuineIntel) [Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz]  CPUID(1)/EAX=000A0655 CPUID(1)/EBX=06100800
11:27:20 (info) CPU #4 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:yes  AVX2:yes  FMA3:yes  AES:yes  RDRAND:yes  RDSEED:yes  Intel(GenuineIntel) [Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz]  CPUID(1)/EAX=000A0655 CPUID(1)/EBX=08100800
11:27:20 (info) CPU #5 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:yes  AVX2:yes  FMA3:yes  AES:yes  RDRAND:yes  RDSEED:yes  Intel(GenuineIntel) [Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz]  CPUID(1)/EAX=000A0655 CPUID(1)/EBX=0A100800
11:27:20 (info) CPU #6 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:yes  AVX2:yes  FMA3:yes  AES:yes  RDRAND:yes  RDSEED:yes  Intel(GenuineIntel) [Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz]  CPUID(1)/EAX=000A0655 CPUID(1)/EBX=01100800
11:27:20 (info) CPU #7 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:yes  AVX2:yes  FMA3:yes  AES:yes  RDRAND:yes  RDSEED:yes  Intel(GenuineIntel) [Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz]  CPUID(1)/EAX=000A0655 CPUID(1)/EBX=03100800
11:27:20 (info) CPU #8 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:yes  AVX2:yes  FMA3:yes  AES:yes  RDRAND:yes  RDSEED:yes  Intel(GenuineIntel) [Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz]  CPUID(1)/EAX=000A0655 CPUID(1)/EBX=05100800
11:27:20 (info) CPU #9 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:yes  AVX2:yes  FMA3:yes  AES:yes  RDRAND:yes  RDSEED:yes  Intel(GenuineIntel) [Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz]  CPUID(1)/EAX=000A0655 CPUID(1)/EBX=07100800
11:27:20 (info) CPU #10 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:yes  AVX2:yes  FMA3:yes  AES:yes  RDRAND:yes  RDSEED:yes  Intel(GenuineIntel) [Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz]  CPUID(1)/EAX=000A0655 CPUID(1)/EBX=09100800
11:27:20 (info) CPU #11 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:yes  AVX2:yes  FMA3:yes  AES:yes  RDRAND:yes  RDSEED:yes  Intel(GenuineIntel) [Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz]  CPUID(1)/EAX=000A0655 CPUID(1)/EBX=0B100800
11:27:20 (info) finally detected CPU features :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:yes  SSE3:yes  SSSE3:yes  SSE41:yes  SSE42:yes  SSE4A:no  AVX:yes  AVX2:yes  FMA3:yes  AES:yes  RDRAND:yes  RDSEED:yes
11:27:20 (info) Specified option(s) (earlier item has more priority) : (none)
11:27:20 (info) Loading startup script : startup.tjs
11:27:20 (info) Trying to read XP3 virtual file system information from : file://./c/program files/fate^stay night[realta nua] ultimate edition/data.xp3
11:27:20 (info) Done. (contains 899 file(s), 899 segment(s))
11:27:20 (info) Rebuilding Auto Path Table ...
11:27:20 (info) Trying to read XP3 virtual file system information from : file://./c/program files/fate^stay night[realta nua] ultimate edition/voice.xp3
11:27:20 (info) Done. (contains 28741 file(s), 28741 segment(s))
11:27:20 (info) Trying to read XP3 virtual file system information from : file://./c/program files/fate^stay night[realta nua] ultimate edition/video.xp3
11:27:20 (info) Done. (contains 3 file(s), 3 segment(s))
11:27:20 (info) Total 29642 file(s) found, 29642 file(s) activated. (32ms)
11:27:20 (info) Rebuilding Auto Path Table ...
11:27:20 (info) Trying to read XP3 virtual file system information from : file://./c/program files/fate^stay night[realta nua] ultimate edition/rule.xp3
11:27:20 (info) Done. (contains 89 file(s), 89 segment(s))
11:27:20 (info) Trying to read XP3 virtual file system information from : file://./c/program files/fate^stay night[realta nua] ultimate edition/sound.xp3
11:27:20 (info) Done. (contains 516 file(s), 516 segment(s))
11:27:20 (info) Trying to read XP3 virtual file system information from : file://./c/program files/fate^stay night[realta nua] ultimate edition/bgm.xp3
11:27:20 (info) Done. (contains 118 file(s), 118 segment(s))
11:27:20 (info) Trying to read XP3 virtual file system information from : file://./c/program files/fate^stay night[realta nua] ultimate edition/etc.xp3
11:27:20 (info) Done. (contains 694 file(s), 694 segment(s))
11:27:20 (info) Trying to read XP3 virtual file system information from : file://./c/program files/fate^stay night[realta nua] ultimate edition/fgimage.xp3
11:27:20 (info) Done. (contains 1991 file(s), 1991 segment(s))
11:27:20 (info) Trying to read XP3 virtual file system information from : file://./c/program files/fate^stay night[realta nua] ultimate edition/bgimage.xp3
11:27:20 (info) Done. (contains 1726 file(s), 1726 segment(s))
11:27:20 (info) Total 34776 file(s) found, 34765 file(s) activated. (16ms)
11:27:20 (info) Rebuilding Auto Path Table ...
11:27:20 (info) Trying to read XP3 virtual file system information from : file://./c/program files/fate^stay night[realta nua] ultimate edition/image.xp3
11:27:20 (info) Done. (contains 1015 file(s), 1015 segment(s))
11:27:20 (info) Total 35791 file(s) found, 35780 file(s) activated. (11ms)
11:27:20 OS : Windows 7 6.1.3505 Service Pack 1 (Win32)
11:27:20 KAG : 3.25 beta 10 TYPE-MOON customized
11:27:20 Kirikiri : 1.4.0.8
11:27:20 (info) Rebuilding Auto Path Table ...
11:27:20 (info) Trying to read XP3 virtual file system information from : file://./c/program files/fate^stay night[realta nua] ultimate edition/patch.xp3
11:27:20 (info) Failed.
11:27:20 ==== An exception occured at initialize.tjs(214)[(top level script) global], VM ip = 694 ====
11:27:20 -- Disassembled VM code --
11:27:20 #(214) if(Storages.isExistentStorage("Config.tjs"))
11:27:20 00000687 const %1, *70	// *70 = (string)"Config.tjs"
11:27:20 00000690 gpd %2, %-2.*71	// *71 = (string)"Storages"
11:27:20 00000694 calld %3, %2.*72(%1)	// *72 = (string)"isExistentStorage"
11:27:20 -- Register dump --
11:27:20 %-7=(object)(object 0x0021C938:0x0021C938)  %-6=(string)"type"  %-5=(int)28  %-4=(void)
11:27:20 %-3=(void)  %-2=(object)(object 0x0031F694:0x00000000)
11:27:20 %-1=(object)(object 0x001F6CD8:0x001F6CD8)  %0=(void)  %1=(string)"Config.tjs"
11:27:20 %2=(object)(object 0x002137F0:0x00000000)  %3=(void)
11:27:20 %4=(object)(object 0x0021D418:0x00000000)  %5=(object)(object 0x012794A8:0x00000000)
11:27:20 %6=(string)"Win32"  %7=(string)")"  %8=(object)(object 0x0021D418:0x00000000)
11:27:20 ---------------------------------------------------------------------------------------------
11:27:20 Script exception raised
file://./c/program files/fate^stay night[realta nua] ultimate edition/patch.xp3 is not XP3 archive or unsupported
11:27:20 trace : startup.tjs(27)[(top level script) global] <-- startup
11:27:20 (info) CPU clock (roughly) : 4110MHz
11:27:40 (info) CPU clock : 4103.9MHz
11:27:51 (info) Rebuilding Auto Path Table ...
11:27:51 (info) Trying to read XP3 virtual file system information from : file://./c/program files/fate^stay night[realta nua] ultimate edition/patch.xp3
11:27:51 (info) Failed.
Monitored process exited.
Initial process has exited (return code: 256)
All monitored processes have exited.
Exit with returncode 256

**Comment by leycec** [comment]
Oh, did you eventually resolve this on your side? **Those are my favourite issues.**

Unrelatedly, it looks like your gamemode installation is busted:

```
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0'
from LD_PRELOAD cannot be preloaded (cannot open
shared object file): ignored.
```

Are you by chance using Ubuntu 20.04 LTS? If so, the above is a common issue caused by Ubuntu 20.04 LTS failing to ship the 32-bit gamemode libs. You can resolve this on your end by [manually reinstalling gamemode from Debian-based `.deb` files](https://github.com/FeralInteractive/gamemode/issues/254#issuecomment-740117461).

Enjoy, Fate/stay night! *Man, wut a VN.*
