### ISSUE TITLE
White screen on initial load, music starts playing, exit menu works

### ISSUE THREAD

**Issue by FinnRG** [leycec/fsnrnue#15]
I installed the game using the lutris one-click installer. If I try to start the visual novel, I see a white screen but I hear the music. I can also see the exit menu if I press escape. After switching the Display quality from High to Low, I can see a constant (non interacteable) image of the start menu, which should have showed on the initial load.

The [Reddit windows installation guide](https://www.reddit.com/r/fatestaynight/comments/6lynfy/fatestay_night_vn_installation_guide_vi/) suggests to  press Alt+Enter to enter the fullscreen mode. This didn't do anything for me.

After checking the other issues I thought that this is maybe relatd to #10, but Dxvk seems to work properly. I have also disabled/enabled the plugins as suggested in the Readme.

Here is the log: https://pastebin.com/e531KeXg (It was too long for github)

**Comment by leycec** [comment]
*ohnoes*

Thanks so much for submitting this detailed issue complete with full error log output. The AMD Radeon RX 5700 XT is such a God-tier beast of a GPU, too; it'd be a shame if we couldn't get this to work for you. I *do* see one darkly suspicious exception pertaining to a screen resolution change:

```
13:39:14 (info) Changing screen mode succeeded
13:39:14 ==== An exception occured at mainwindow.tjs(1029)[(property setter) fullScreen], VM ip = 837 ====
13:39:14 -- Disassembled VM code --
13:39:14 #(1029) 			windowSizeMenu.enabled	= !fullScreen;	//	EBhETCY̐ݒ̓EBhE\̂Ƃ̂
13:39:14 00000831 gpd %1, %-2.*97	// *97 = (string)"fullScreen"
13:39:14 00000835 lnot %1
13:39:14 00000837 gpd %2, %-2.*98	// *98 = (string)"windowSizeMenu"
13:39:14 -- Register dump --
13:39:14 %-6=(int)1  %-5=(int)-1  %-4=(void)  %-3=(int)1  %-2=(object)(object 0x009EE4E0:0x00000000)
13:39:14 %-1=(object)(object 0x059CC2B0:0x059CC2B0)  %0=(void)  %1=(int)0
13:39:14 %2=(object)(object 0x04E5F4B0:0x04E5F4B0)  %3=(int)0  %4=(int)1080
13:39:14 %5=(object)(object 0x04E5F4B0:0x04E5F4B0)  %6=(real)644  %7=(real)644
13:39:14 -------------------------------------------------------------------------------------------------
13:39:14 tXN[[hɈڍsł܂ł : Member "windowSizeMenu" does not exist
```

Unfortunately, you're the first ~~guinea pig~~ hapless human in the long history of the Internet tubes to hit that. Google shows nothing! Zilch. But it certainly does seem relevant, doesn't it? `</sigh>`

The only other mild code smell are these non-fatal warnings much further down in the logs:

```
13:39:15 ================================================================================
13:39:15 Scenario loaded : Q[j[.ks
13:39:15 Q[j[.ks : @if exp="typeof(global.gamemenu) == 'undefined'"
13:39:15 Warning: Substitution in boolean context (use form of '(A=B)!=0' to compare to zero) at fontselectlayer.tjs line 208
13:39:15 Warning: Substitution in boolean context (use form of '(A=B)!=0' to compare to zero) at fontselectlayer.tjs line 209
13:39:15 Warning: Substitution in boolean context (use form of '(A=B)!=0' to compare to zero) at statusmenulayer.tjs line 350
13:39:15 Warning: Substitution in boolean context (use form of '(A=B)!=0' to compare to zero) at statusparameterlayer.tjs line 88
13:39:15 Q[j[.ks : @endif
```

Those are probably fine, so we are stumped. As a last-ditch move of unadulterated desperation, would you mind trying to:

1. **Disable DXVK in Lutris:** 
   1. Run Lutris.
   1. Right-click the Fate/stay night entry.
   1. Click the Configure menu item.
   1. Click the Runner options tab.
   1. Disable the Enable DXVK/VKD3D setting.
   1. You're done. Praise Ilya!
1. **Disable D3D9 in Lutris,** similarly to above.
2. **Try a different WINE version.** This is probably more work than you'd care to invest in this, but this *could* be an issue specific to a WINE version. We've currently hard-locked the installer to WINE 6.1.3 (`lutris-6.1-3-x86_64`). In theory, changing that to a significantly older or newer WINE version *could* alleviate your suffering and solve world hunger.

We sob unconsolably in advance if none of the above yield joy. :sob:

**Comment by FinnRG** [comment]
@leycec Thank you very much. I've disabled DXVK and the game now runs perfectly.

**Comment by leycec** [comment]
**Fantastic!** A happy resolution is cause for jubilation and H-scenes. I'll append a new entry to our FAQ detailing this issue and its resolution, too. :+1:
