### ISSUE TITLE
Monitored process exited. Initial process has exited (return code: 256) Exit with return code 256

### ISSUE THREAD

**Issue by crimpsumpski** [leycec/fsnrnue#25]
Started initial process 34806 from /home/crim/.local/share/lutris/runtime/winetricks/winetricks --unattended d3dx9 quartz vcrun2015 win7
Start monitoring process.
Executing mkdir -p /home/crim/Games
Using winetricks 20210206-next - sha256sum: 87dabceee91cbb4c58928d3ddeee57449e591df1b1e7f6011b2eec80e5047eda with wine-6.21.r0.g63c3baa9 ( TkG Staging Esync Fsync ) and WINEARCH=win32
Executing w_do_call d3dx9
Executing mkdir -p /home/crim/Games
Executing load_d3dx9 
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp -L -F *d3dx9*x86* /home/crim/.cache/winetricks/directx9/directx_Jun2010_redist.exe
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/apr2005_d3dx9_25_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/apr2005_d3dx9_25_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/apr2006_d3dx9_30_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/apr2006_d3dx9_30_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/apr2007_d3dx9_33_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/apr2007_d3dx9_33_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/aug2005_d3dx9_27_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/aug2005_d3dx9_27_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/aug2007_d3dx9_35_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/aug2007_d3dx9_35_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/aug2008_d3dx9_39_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/aug2008_d3dx9_39_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/aug2009_d3dx9_42_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/aug2009_d3dx9_42_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/dec2005_d3dx9_28_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/dec2005_d3dx9_28_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/dec2006_d3dx9_32_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/dec2006_d3dx9_32_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/feb2005_d3dx9_24_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/feb2005_d3dx9_24_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/feb2006_d3dx9_29_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/feb2006_d3dx9_29_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/jun2005_d3dx9_26_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/jun2005_d3dx9_26_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/jun2007_d3dx9_34_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/jun2007_d3dx9_34_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/jun2008_d3dx9_38_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/jun2008_d3dx9_38_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/jun2010_d3dx9_43_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/jun2010_d3dx9_43_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/mar2008_d3dx9_37_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/mar2008_d3dx9_37_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/mar2009_d3dx9_41_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/mar2009_d3dx9_41_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/nov2007_d3dx9_36_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/nov2007_d3dx9_36_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/nov2008_d3dx9_40_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/nov2008_d3dx9_40_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/oct2006_d3dx9_31_x86.cab
/home/crim/Games/fatestay-night/dosdevices/c:/windows/temp/oct2006_d3dx9_31_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Using native override for following DLLs: d3dx9_24 d3dx9_25 d3dx9_26 d3dx9_27 d3dx9_28 d3dx9_29 d3dx9_30
Executing /home/crim/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/bin/wine regedit /S C:\windows\Temp\override-dll.reg
018c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
018c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0194:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0194:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01a8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01a8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
Using native override for following DLLs: d3dx9_31 d3dx9_32 d3dx9_33 d3dx9_34 d3dx9_35 d3dx9_36 d3dx9_37
Executing /home/crim/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/bin/wine regedit /S C:\windows\Temp\override-dll.reg
01b0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01b0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01b8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01b8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
Using native override for following DLLs: d3dx9_38 d3dx9_39 d3dx9_40 d3dx9_41 d3dx9_42 d3dx9_43
Executing /home/crim/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/bin/wine regedit /S C:\windows\Temp\override-dll.reg
01c0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01c0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01c8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01c8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
Executing w_do_call quartz
Executing mkdir -p /home/crim/Games
Executing load_quartz 
------------------------------------------------------
warning: Checksum for /home/crim/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe did not match, but --force was used, so ignoring and trying anyway.
------------------------------------------------------
Executing cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp -L -F x86_microsoft-windows-directshow-core_31bf3856ad364e35_6.1.7601.17514_none_a877a1cc4c284497/quartz.dll /home/crim/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe
/home/crim/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe: no valid cabinets found
------------------------------------------------------
warning: Note: command cabextract -q -d /home/crim/Games/fatestay-night/dosdevices/c:/windows/temp -L -F x86_microsoft-windows-directshow-core_31bf3856ad364e35_6.1.7601.17514_none_a877a1cc4c284497/quartz.dll /home/crim/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe returned status 1. Aborting.
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
Exit with return code 256

**Comment by kaasknak** [comment]
Hey!

Seems you are running into some problems. 
Can you try to post a log using [this](https://github.com/leycec/fsnrnue#nice-magic-words-you-wizardperson-what-are-these-log-error-messages) method?

Also it seems you are getting the same error as we got in a previous issue [here](https://github.com/leycec/fsnrnue/issues/24). Maybe what is written there can help you. 

A often occurring problem is that patching fails due to data limits. This is out of our control as we don't host the patches but you should be able to fix this by manually redownloading the patches as described [here](https://github.com/leycec/fsnrnue#okay-i-am-indeed-seeing-this-exception-i-think)

**Comment by kaasknak** [comment]
With no further input this issue has nowhere to go.
Feel free to reopen it if you are still experiencing the issue.

**Comment by leycec** [comment]
Thanks for the bang-up oversight, @kaasknak! So relieved we brought you on board to (wo)man the helm in my "absence." :sweat_smile:
