### ISSUE TITLE
online install doesnt work

### ISSUE THREAD

**Issue by noxarad** [leycec/fsnrnue#29]
well not big of a problem basically the installer requires wine 6.14-3 but that doesnt exist
well i did just change the wine version to 6.14-4 by downloading the script but definitely should be fixed :P

**Comment by kaasknak** [comment]
> well not big of a problem basically the installer requires wine 6.14-3 but that doesnt exist
> 
> well i did just change the wine version to 6.14-4 by downloading the script but definitely should be fixed :P

I am a bit lost with this problem. The online installer on the lutris website is outdated. I have tried updating it several times now but it seems it never actually gets accepted by the lutris team. :s
@leycec do you have any fancy ideas?

**Comment by leycec** [comment]
**Gah!** My fancy idea is (...*wait for it*) for me to reluctantly sigh and then update the Lutris-hosted installer myself. Sadly, I'm super-strapped for volunteer open-source time. I'm finding it hard to even devote a hot minute to @beartype. That's when you know things are dire, folks.

Once I excrete `beartype 0.11.0` sometime later this week, I'll try really, *really* hard to throw an hour or two of quality "family" time towards this. Everyone has my permission to beat with a limp udon noodle if I fail to do this by this Friday. :ramen: 

Oh – and thanks so much, @kaasknak, for continuing to stay on time of this repo. You're breathtaking. I mean... not quite Sakura breathtaking. But you're getting there, buddy!

**Comment by matildepark** [comment]
What I did was:

- In Lutris, download wine-6.25-6 (I think it was that) under "manage Wine installations"
- Uncomment the part in the .yml file where it says `wine: version:` etc. and set it to that version
- Use that edited .yml file

It installed and everything was hunky dory (so far). Very neat to see it working on a Steam Deck.

**Comment by matildepark** [comment]
Oh, I also needed to get the .xp3 patch files myself from the link provided later on in the README afterward since everything except the English translation was a 2kb placeholder.

**Comment by kaasknak** [comment]
> Oh, I also needed to get the .xp3 patch files myself from the link provided later on in the README afterward since everything except the English translation was a 2kb placeholder.

This is unfortunately just the way things are. The patches are hosted externally and affected by datalimits.

@leycec did you succeed at changing the lutris server sided installer?

**Comment by leycec** [comment]
**Gah!** I am a bad, bad weeb. This means I did nothing. Ilya is most displeased. :princess: 

Thankfully, I have a valid excuse. I couldn't help but notice the Beast's Lair has released *quite* a [few new iterations of their **Ultimate Edition** installer under new management](https://forums.nrvnqsr.com/showthread.php/9101-Fate-Stay-Night-Realta-Nua-Ultimate-Edition-2022). In fact, **v1.1.2** was released just a few weeks ago. We're now lagging embarrassingly behind. I'd like us to fix that. By "us," I mean someone who is not me.

The most exciting addition is support for ``patch_vita_ost.xp3``: the **remixed OST** from the Vita and mobile releases! We all give thanks for that. In my awful opinion, the original OST is probably the weakest aspect of the original VN; it'd be fascinating to see (well, *hear*) whether the remixed OST changes my awful opinion.

@kaasknak: Your time is also scarce and valuable. But – if you *do* happen to find a free moment in your hectic schedule – would it be feasible for you (or someone like you) to bump our Lutris installer to the newest version of the Ultimate Edition? And thanks *soooo* much for continuing to shepherd this repo in the right direction.

**Comment by matildepark** [comment]
What I noticed was this installer at least showed the title screen of the game. My last install (I presumed it was a newer installer?) just jumped in.

**Comment by leycec** [comment]
That's... **a bad sign.** Thanks for the depressing suggestion that we're eternally stuck on 0.9.x. I will now eat ice cream chronically for the entire weekend.

Still, things could be worse. By doing absolutely nothing, we've at least ensured that the title screen still shows up! Laziness prevails after all, everyone.

**Comment by matildepark** [comment]
Why is it bad? I could go update my install.

**Comment by matildepark** [comment]
I didn’t really suggest anything. I haven’t played this game yet!

**Comment by leycec** [comment]
**Oh.** That's great, then. I took this comment...

> My last install (I presumed it was a newer installer?) just jumped in.

...to mean that newer Ultimate Edition installers fail to run properly under Linux. But if that's *not* actually the case, that's wondrous news!

In any case, I'll update our Lutris-hosted installer tonight to *finally* close out this issue. :sweat:

**Comment by leycec** [comment]
**Resolved...** hopefully. Please reopen this issue if our Lutris-hosted installer continues failing you, please. Until then, may all your Steam Deck belong to Ilya.

**Comment by matildepark** [comment]
> **Oh.** That's great, then. I took this comment...
> 
> > My last install (I presumed it was a newer installer?) just jumped in.
> 
> ...to mean that newer Ultimate Edition installers fail to run properly under Linux. But if that's _not_ actually the case, that's wondrous news!
> 
> In any case, I'll update our Lutris-hosted installer tonight to _finally_ close out this issue. 😓

No, I mean it literally just starts the story! I figured the title screen was an improvement in some way! I’ll update and see …

**Comment by leycec** [comment]
**Indeed.** The title screen should *absolutely* be the landing page. You're not supposed to know this, but the title screen actually changes after you complete each route. *And the new title screens are awesome.*

If newer versions accidentally bypass the title screen for the first route and leap straight into the first route, that would be both bad and sad. Weep for us, cat emoji. Weep! :crying_cat_face: 

Oh – and I've opened up a [new issue tracking whether or not we can (or even *should*) support the newly released **Ultimate Edition v1.1.2** installer](https://github.com/leycec/fsnrnue/issues/30). Drop us all a line there if you find out anything juicy.
