### ISSUE TITLE
[Feature Request] Bump to Ultimate Edition v1.1.2

### ISSUE THREAD

**Issue by leycec** [leycec/fsnrnue#30]
I couldn't help but notice the Beast's Lair has released *quite* a [few new iterations of their **Ultimate Edition** installer under new management](https://forums.nrvnqsr.com/showthread.php/9101-Fate-Stay-Night-Realta-Nua-Ultimate-Edition-2022). In fact, **v1.1.2** was released just a few weeks ago. We're now lagging embarrassingly behind. I'd like us to fix that. By "us," I mean someone who is not me.

The most exciting addition is support for ``patch_vita_ost.xp3``: the **remixed OST** from the Vita and mobile releases! We all give thanks for that. In my awful opinion, the original OST is probably the weakest aspect of the original VN; it'd be fascinating to see (...okay, *hear*) whether the remixed OST changes my awful opinion.

@kaasknak: Your time is also scarce and valuable. But – if you *do* happen to find a free moment in your hectic schedule – would it be feasible for you (or someone like you) to bump our Lutris installer to the newest version of the Ultimate Edition? And thanks *soooo* much for continuing to shepherd this repo in the right direction.

**Comment by kaasknak** [comment]
I did look into this (nearly a year ago it seems) https://github.com/leycec/fsnrnue/issues/2#issuecomment-994996950

I will see if I can be of any help but from what I saw in the threads back then it seems to absolutely mess everything up. Maybe it is best if we create a separate branch for the up to date version and keep the master branch at 0.9 now and call it stable(ish).

**Comment by leycec** [comment]
**Gah!** Thanks a heap (of tatami mats) for the gentle reminder.

"Absolutely mess everything up" reads equivalent to "Let's not do this... *maybe ever.*" Since the current obsolete version actually works as advertised, we'll probably just stick with 0.9.x for the foreseeable future. On the bright side, nobody needs to do anything to make that happen. Laziness, you prevail again. :sleepy:

**Comment by mmgmp** [comment]
Hi, I created a Lutris install script that installs the newest version of ultimate edition.
You can find it here: https://github.com/mmgmp/fsnrnue-updated

**Comment by TDCMC** [comment]
Since I've bumped the version, I will be closing this issue as completed and any problems that occur with the new installer will be reported as separate issues.
