### ISSUE TITLE
Migrating saves from older installation?

### ISSUE THREAD

**Issue by SvartTe** [leycec/fsnrnue#33]
Hi,
I made a fresh install using the offline installer last night and wanted to take the saves I have from an earlier install to this one. Unfortunately I'm met with the error

`Script exception raised
Cannot convert the variable type ((void) to Object)`

Pouring through the Beasts lair thread this seems to be caused by incompatible patches. Have I understood that right?

**Comment by leycec** [comment]
**Gah!** So sorry for your pain, @SvartTe. Sadly, nobody here (including me) has any idea whatsoever. Beasts Lair is always right, though. Those guys know. :disappointed: 

Let's be honest with ourselves at 2:00AM on a Friday night: this repository is mostly unmaintained at this point. F/SN is a *phenomenal* VN – but the 「Fate/stay night REMASTERED」 announcement this January took most of the wind out of our sails. The official REMASTERED console edition will almost certainly be better than this unofficial fan-based Ultimate Edition. <sup>*...ignoring H-scenes, anyway – which are mostly hilariously awful, anyway.*</sup>

If recovering your saves fails, have you considered just waiting for the REMASTERED to drop and replaying that from scratch? Either way, Ilya weeps for you. :sob:

**Comment by kaasknak** [comment]
The way things are going with the beast lair complete overhaul and the remastered version it is pretty safe to say that this repo could be considered a stable-ish version of the beast lair's version a couple of versions ago (version version version). I still play it and enjoy it but I honestly don't have the time to bring this repo up to the newest stuff the beast lair churns out. @leycec is very busy with his own project from what I saw as well so I guess we could say we are mainly just ironing out the occasional bug still found. 

Unless someone else has time to rewrite things (or subscribes to @leycec on Github so he gets paid) I don't see this repo moving forward soon. Sad but it is what it is.

**Comment by SvartTe** [comment]
I completely understand, time is a finite resource. For any future seekers, I did manage to fix my problem. It seems that my previous installationwas using patches taken straight from the Beasts Lair, I'm guessing it was primarily that I had chosen to use the new translation patch that caused my problems. So I guess now I can continue reading the definitely completely happy ending, where nothing more bad happens to my favourite mini-murder machine, Illya!

Thanks for your work guys, seriously.

**Comment by leycec** [comment]
Thanks for being so understanding... *and huge congrats for restoring your precious ~~sanity~~ saves!* The most precious resource is your own time. You have saved yours. Mini murder-machine Ilya approves.

Here's hoping for an Ilya True Golden Route in the Remastered. Do it, Type-Moon. You cowards! :smiling_face_with_tear:
