### ISSUE TITLE
"Error: Could not find XP3 mark." during installation

### ISSUE THREAD

**Issue by viniciusEdXavier** [leycec/fsnrnue#34]
Hi! Whenever I try to install (online OR offline), the following message shows up:
![image](https://github.com/leycec/fsnrnue/assets/43896829/5ff80681-07ed-4e40-b566-530e45dea1cf)

Here is the Lutris log up until this point:
[log.txt](https://github.com/leycec/fsnrnue/files/15395899/log.txt)

I'm using Ubuntu 22.04.4 LTS, is there something I can do to fix this?
Thanks in advance!

**Comment by TDCMC** [comment]
Hello, it seems that you're using the lutris hosted installer which has not yet been updated to the newest version. (Although I have submitted a request to do so.) Please download the yml file from the github repository and use that instead.

1. Click on the green "Code" button > Download ZIP
2. Extract the zip file
3. open lutris > click on the + button > Install from a local install script > Select the yml file located in the lutris folder.

Also please use `wine-ge-8-26` as that version fixes some issues that occurred in the 7.X version.
If the issue persists, upload the new log file as well.

**Comment by viniciusEdXavier** [comment]
Thank you so much for the reply! During this process I ended up figuring the problem was in the extract step for the install, so I just extracted the files manually before the installation, and now it's working. Maybe the problem was in my 7za version or something, since I used unar for the manual extract.

**Comment by leycec** [comment]
@TDCMC: **Thank you so much!** You're so incredibly helpful. Would you like commit access to this repository? Just say the word, bro. Also...

> Hello, it seems that you're using the lutris hosted installer which has not yet been updated to the newest version. (Although I have submitted a request to do so.)

*...amazing intensifies.* Would you mind submitting a pull request (PR) updating this repository to the newest version, too? It'd be wonderful to be up-to-date with the official Beast's Lair installer. Anyway, thanks again. Due to @beartype, I lack the time this repository deserves. Emoji cat cries. :crying_cat_face:

**Comment by TDCMC** [comment]
> @TDCMC: **Thank you so much!** You're so incredibly helpful. Would you like commit access to this repository? Just say the word, bro. Also...
> 
> > Hello, it seems that you're using the lutris hosted installer which has not yet been updated to the newest version. (Although I have submitted a request to do so.)
> 
> _...amazing intensifies._ Would you mind submitting a pull request (PR) updating this repository to the newest version, too? It'd be wonderful to be up-to-date with the official Beast's Lair installer. Anyway, thanks again. Due to @beartype, I lack the time this repository deserves. Emoji cat cries. 😿

Already done it, I changed my username but in january you made me a contributer.

**Comment by TDCMC** [comment]
> Thank you so much for the reply! During this process I ended up figuring the problem was in the extract step for the install, so I just extracted the files manually before the installation, and now it's working. Maybe the problem was in my 7za version or something, since I used unar for the manual extract.

That's great! But I still recommend updating your install (Both the ultimate edition which has since been updated from v0.9.1 to v1.1.4 and your wine version to fix the major issues related to the movie playback.)

**Comment by leycec** [comment]
*...lol.* Please ignore [my prior ridiculous comment](https://github.com/leycec/fsnrnue/issues/34#issuecomment-2253752746). I didn't realize you already *were* a collaborator. Where have I been all these years!? Probably right here. What I have been doing all these years!? Probably reading too many visual novels. :sweat_smile: 

> I changed my username...

**Ho, ho, ho.** So, the truth comes out at last. Thanks so much again for your tremendous volunteerism, @TDCMC. I'd promote you even higher from Collaborator to repository co-Owner, but GitHub doesn't let me do that. I shake my pasty fist at Microsoft.
