### ISSUE TITLE
**Ahah!** @gourrykun [helpfully identified the culprit](https://github.com/leycec/fsnrnue/issues/2#issuecomment-620439559) at #1:

### ISSUE THREAD

**Issue by wachiragetkul** [leycec/fsnrnue#7]
**Ahah!** @gourrykun [helpfully identified the culprit](https://github.com/leycec/fsnrnue/issues/2#issuecomment-620439559) at #1:

> Currently this step often fails due to disk quota exceeded.

Welp. It was Option 2 after all. `</sigh>`

On the bright side, this isn't our fault. On the dark side, the Ultimate Installer team at [Beast's Lair](https://forums.nrvnqsr.com) now desperately needs to upload their patchset to a more reliable host. For reasons stated above, that can't be GitHub and shouldn't be GoogleDrive. If anyone who is not me would like to open up a discussion with our [Beast's Lair sempais](https://forums.nrvnqsr.com) about this, that would be just great.

Until then, our hands are gently tied by Ilya.

_Originally posted by @leycec in https://github.com/leycec/fsnrnue/issues/3#issuecomment-620993699_

**Comment by wachiragetkul** [comment]
jsod

**Comment by wachiragetkul** [comment]
> **Ahah!** @gourrykun [helpfully identified the culprit](https://github.com/leycec/fsnrnue/issues/2#issuecomment-620439559) at #1:
> 
> > Currently this step often fails due to disk quota exceeded.
> 
> Welp. It was Option 2 after all. `</sigh>`
> 
> On the bright side, this isn't our fault. On the dark side, the Ultimate Installer team at [Beast's Lair](https://forums.nrvnqsr.com) now desperately needs to upload their patchset to a more reliable host. For reasons stated above, that can't be GitHub and shouldn't be GoogleDrive. If anyone who is not me would like to open up a discussion with our [Beast's Lair sempais](https://forums.nrvnqsr.com) about this, that would be just great.
> 
> Until then, our hands are gently tied by Ilya.
> 
> _Originally posted by @leycec in [#3 (comment)](https://github.com/leycec/fsnrnue/issues/3#issuecomment-620993699)_

**Comment by leycec** [comment]
I... don't quite understand. What's "jsod"? I'm not hip with the Zoomer lingo, but even I'm pretty sure that's not a thing.

Anyway, [upstream has yet to resolve this issue at the Beast's Lair](https://forums.nrvnqsr.com/showthread.php/8229-Fate-Stay-Night-Realta-Nua-Ultimate-Edition?p=3100968&viewfull=1#post3100968):

> I apologize, but there is no ETA for the [next stable] release. 

That means our hands are still tied here. Sorry, bro! :crying_cat_face:
